### DISCUSSION TITLE
Anyone know how to get a custom wake word working with a Dockerized home assistant / wyoming setup?

### DISCUSSION THREAD

**Discussion by trisweb** [fwartner/home-assistant-wakewords-collection#28] [Q&A] [answered]
Hey folks, love this collection and would love to use some of the custom wake words.

The problem I'm running into is, I've got my home assistant setup using docker-compose on two different PCs (one is better at wake word and TTS/STT jobs, so it's kind of nice).

But I can't get any of the custom wake words working with this setup.

In my wyoming-openwakeword container I have the following docker compose config:

```yaml
version: '3.3'
services:
    wyoming-openwakeword:
        restart: unless-stopped
        volumes:
            - './data:/data'
            - './custom:/custom'
        ports:
            - '10400:10400'
        image: rhasspy/wyoming-openwakeword
        command: " --preload-model 'ok_computer' --custom-model-dir /custom"
```

I've placed several .tflite models from this repo in the /custom folder, and reloaded the docker container. But they're still not showing up in the Home Assistant assist dropdown for wake words... any ideas?
